export let Realproducts = [
    {
        id: 1,
        nameOfProduct: 'Lorem Ipsum product',
        price: 19,
        image: 'images/femalebag6.webp',
        discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem amet fugit sequi ullam facilis cum reprehenderit dicta incidunt accusantium ipsa iste perferendis, mollitia dolorem ab architecto. Laborum recusandae tempore dicta!',
        timeUpdated: '',
        category: 'women',
        categoryAll: 'all',
        product: 'bags',
        stock: 5,
        stockCount: 1,
        defaultPrice: 19
    },
    {
        id: 2,
        nameOfProduct: 'Lorem Ipsum product',
        price: 1,
        image: 'images/malebag73.webp',
        discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem amet fugit sequi ullam facilis cum reprehenderit dicta incidunt accusantium ipsa iste perferendis, mollitia dolorem ab architecto. Laborum recusandae tempore dicta!',
        timeUpdated: '',
        category: 'men',
        categoryAll: 'all',
        product: 'bags',
        stock: 5,
        stockCount: 1,
        defaultPrice: 1
    },
    {
        id: 3,
        nameOfProduct: 'Lorem Ipsum product',
        price: 5,
        image: 'images/femalecap37.webp',
        discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem amet fugit sequi ullam facilis cum reprehenderit dicta incidunt accusantium ipsa iste perferendis, mollitia dolorem ab architecto. Laborum recusandae tempore dicta!',
        timeUpdated: '',
        category: 'women',
        categoryAll: 'all',
        product: 'hats',
        stock: 5,
        stockCount: 1,
        defaultPrice: 5
    },
    {
        id: 4,
        nameOfProduct: 'Lorem Ipsum product',
        price: 2,
        image: 'images/femaletrouser25.webp',
        discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem amet fugit sequi ullam facilis cum reprehenderit dicta incidunt accusantium ipsa iste perferendis, mollitia dolorem ab architecto. Laborum recusandae tempore dicta!',
        timeUpdated: '',
        category: 'women',
        categoryAll: 'all',
        product: 'trousers',
        stock: 5,
        stockCount: 1,
        defaultPrice: 2
    },
    {
        id: 6,
        nameOfProduct: 'Lorem Ipsum product',
        price: 7,
        image: 'images/maletrouser7.webp',
        discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem amet fugit sequi ullam facilis cum reprehenderit dicta incidunt accusantium ipsa iste perferendis, mollitia dolorem ab architecto. Laborum recusandae tempore dicta!',
        timeUpdated: '',
        category: 'men',
        categoryAll: 'all',
        product: 'trousers',
        stock: 5,
        stockCount: 1,
        defaultPrice: 7
    },
    {
        id: 7,
        nameOfProduct: 'Lorem Ipsum product',
        price: 34,
        image: 'images/femaleShoe2.jpg',
        discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem amet fugit sequi ullam facilis cum reprehenderit dicta incidunt accusantium ipsa iste perferendis, mollitia dolorem ab architecto. Laborum recusandae tempore dicta!',
        timeUpdated: '',
        category: 'women',
        categoryAll: 'all',
        product: 'shoes',
        stock: 5,
        stockCount: 1,
        defaultPrice: 34
    },
    {
        id: 8,
        nameOfProduct: 'Lorem Ipsum product',
        price: 11,
        image: 'images/maleShoe3.webp',
        discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem amet fugit sequi ullam facilis cum reprehenderit dicta incidunt accusantium ipsa iste perferendis, mollitia dolorem ab architecto. Laborum recusandae tempore dicta!',
        timeUpdated: '',
        category: 'men',
        categoryAll: 'all',
        product: 'shoes',
        stock: 5,
        stockCount: 1,
        defaultPrice: 11
    },
    {
        id: 9,
        nameOfProduct: 'Lorem Ipsum product',
        price: 19,
        image: 'images/femaletop1b.webp',
        discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem amet fugit sequi ullam facilis cum reprehenderit dicta incidunt accusantium ipsa iste perferendis, mollitia dolorem ab architecto. Laborum recusandae tempore dicta!',
        timeUpdated: '',
        category: 'women',
        categoryAll: 'all',
        product: 'tops',
        stock: 5,
        stockCount: 1,
        defaultPrice: 19
    }
  ]
