export let products = [
    {
        id: 1,
        nameOfProduct: 'product one',
        price: '$'+19+'.00',
        image: '',
        color: '',
        discription: '',
        timeUpdated: '',
        size: '',
        category: '',
        product: '',
        brand: ''
    },
    {
        id: 2,
        nameOfProduct: 'product two',
        price: '$'+1+'.00',
        image: '',
        color: '',
        discription: '',
        timeUpdated: '',
        size: '',
        category: '',
        product: '',
        brand: ''
    },
    {
        id: 3,
        nameOfProduct: 'product three',
        price: '$'+5+'.00',
        image: '',
        color: '',
        discription: '',
        timeUpdated: '',
        size: '',
        category: '',
        product: '',
        brand: ''
    },
    {
        id: 4,
        nameOfProduct: 'product four',
        price: '$'+2+'.00',
        image: '',
        color: '',
        discription: '',
        timeUpdated: '',
        size: '',
        category: '',
        product: '',
        brand: ''
    },
    {
        id: 5,
        nameOfProduct: 'product five',
        price: '$'+23+'.00',
        image: '',
        color: '',
        discription: '',
        timeUpdated: '',
        size: '',
        category: '',
        product: '',
        brand: ''
    },
    {
        id: 6,
        nameOfProduct: 'product six',
        price: '$'+7+'.00',
        image: '',
        color: '',
        discription: '',
        timeUpdated: '',
        size: '',
        category: '',
        product: '',
        brand: ''
    },
    {
        id: 7,
        nameOfProduct: 'product seven',
        price: '$'+34+'.00',
        image: '',
        color: '',
        discription: '',
        timeUpdated: '',
        size: '',
        category: '',
        product: '',
        brand: ''
    },
    {
        id: 8,
        nameOfProduct: 'product eight',
        price: '$'+11+'.00',
        image: '',
        color: '',
        discription: '',
        timeUpdated: '',
        size: '',
        category: '',
        product: '',
        brand: ''
    },
    {
        id: 9,
        nameOfProduct: 'product nine',
        price: '$'+19+'.00',
        image: '',
        color: '',
        discription: '',
        timeUpdated: '',
        size: '',
        category: '',
        product: '',
        brand: ''
    },
    {
        id: 10,
        nameOfProduct: 'product ten',
        price: '$'+19+'.00',
        image: '',
        color: '',
        discription: '',
        timeUpdated: '',
        size: '',
        category: '',
        product: '',
        brand: ''
    },
]